### ISSUE TITLE
HAL Target component appears in grasshopper component dropdown menu when typing "mesh"

### ISSUE THREAD

**Issue by ldemt** [HALRobotics/Beta#15]
Hello,

Installation Configuration:
HAL.McNeel.V5.1.0.17278.2-beta
HAL.ABB.1.0.17278.2-beta

Here is the bug : when I type "mesh", the HAL target component appears first

![1710-15-halbugmesh](https://user-images.githubusercontent.com/33175889/32839861-1d84dc58-ca16-11e7-9c59-7743850b4b14.jpg)

Also when I type "move" i get the HAL Move component first. I use more often the vanilla grasshopper Move component so this is not comfortable imho.

Thank you

**Comment by thibaultschwartz** [comment]
Hi Idemt,
This is due to a bad component suggestion sorting algorithm in Grasshopper, which does not prioritize native components. I could add some settings to entirely disable the registration of HAL content in the search menu, or add the presence of a prefix (i.e: HAL Move) to decrease the score of HAL components. I am adding this on the todo list.
Best

**Comment by thibaultschwartz** [comment]
fixed in next release
