### ISSUE TITLE
Missing components at file opening in Rhino6

### ISSUE THREAD

**Issue by celiabug** [HALRobotics/Beta#28]
I have HAL properly installed, I see all components in grasshopper both in Rh5 and Rh6
When opening my file in Rh6 though, I get an error message stating that some components are missing, even though they are properly installed. Some of the HAL components seem to have loaded properly, but not all of them.
The file loads fine in Rh5.

[Error_message_HAL_RH6.zip](https://github.com/HALRobotics/Beta/files/2097424/Error_message_HAL_RH6.zip)

**Comment by sebandraos** [comment]
Which version of HAL do you have installed? I have no issues opening the Grasshopper file attached. The file, however, has a fairly severe programming issue for simulation and export in that there are several procedures leading into the controller. Between the Merge of your several Moves and the controller you should use a Combine Actions component to sequence the actions rather than running them in parallel.
