### ISSUE TITLE
Lagging display for actions

### ISSUE THREAD

**Issue by lionpeloux** [HALRobotics/Beta#49]
Hi,

When a solution is solved and TCP trace is shown on the screen, it is lagging a lot with the **draw shaded preview** option enable in GH, while it is much more faster with the **draw wireframe preview** option enable in GH.

Maybe in this particular case lagging comes from the marking of solving errors as spheres on the path ? Would it be faster to use [DrawPoint](https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Display_DisplayPipeline_DrawPoint_4.htm) with a certain [PointStyle](https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Display_PointStyle.htm) ? In my case I got 1500 errors ...

In shaded mode, preview is lagging a lot (10s) :
<img width="1680" alt="capture d ecran 2018-09-19 a 14 37 29" src="https://user-images.githubusercontent.com/951626/45754109-017e6680-bc1b-11e8-9667-0404c4c035bb.png">

In wireframe mode, preview is fast enough :
<img width="1680" alt="capture d ecran 2018-09-19 a 14 37 43" src="https://user-images.githubusercontent.com/951626/45754154-1f4bcb80-bc1b-11e8-8c64-8dedf1ef8a70.png">

# Config

`HAL 1.2.6 beta`
`Rhino 6 SR8`
`MACOS 10.13.6` 
`VMWare Fusion 10.1.0` with `WIN7 PRO SP1`

[LaggingCombineAction.zip](https://github.com/HALRobotics/Beta/files/2397071/LaggingCombineAction.zip)

**Comment by thibaultschwartz** [comment]
Thanks for the report, there was indeed a bug in the singularity display, which is now fixed in the coming release. Please also note that your simulation will be faster if you improve the model quality of your track (the mesh of the "wagon"in particular weighs near 10k faces. It can easily be remodeled to be cleaner and weigh around 200 faces). Don't hesitate to also use the ReduceMesh command in Rhino to make meshes lighter when you create your parts.
